config/routes.rb
Goodwill::Application.routes.draw do
  devise_for :users
  resources :products, only: [:create, :destroy]

  resources :users

  root to: 'static_pages#home'

  get '/about', to: 'static_pages#about', as: 'about'
  get '/token' => 'home#token', as: :token

  devise_scope :user do
    get "/login" => "devise/sessions#new"
  end

  devise_scope :user do
    delete "/logout" => "devise/sessions#destroy"
  end

  devise_scope :user do
    get "/sign_up" => "devise/registrations#new"
  end

  post 'check_email', to: 'users#check_email'

  

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user

  validates :product_name, presence: true, length: { maximum: 50 }
  validates :product_price, presence: true, numericality: {greater_than: 0 }

  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :products

  before_save { |user| user.email = email.downcase }

  #has_secure_password

  validates :username, presence: true, length: { maximum: 50 }
  validates :email, presence:   true,
            format:     { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
            uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  def feed
    products
  end

  #def User.new_remember_token
  #  SecureRandom.urlsafe_base64
  #end
  #
  #def User.encrypt(token)
  #  Digest::SHA1.hexdigest(token.to_s)
  #end
  #
  #private
  #def create_remember_token
  #  self.remember_token = User.encrypt(User.new_remember_token)
  #end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit! }
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :correct_user,   only: :destroy

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        @feed_items = []
        render 'static_pages/home'
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end


  def correct_user
    @products = current_user.products.find_by(id: params[:id])
    rescue
    redirect_to root_url if products.nil?
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:product_name, :product_price, :product_description)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
      @feed_items = Product.all.paginate(page: params[:page])
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_filter :signed_in_user, only: [:index, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.paginate(page: params[:page])

    respond_to do |format|
      format.html
      format.json { render json: @users }
      format.xml { render xml: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @products = @user.products.paginate(page: params[:page])

    respond_to do |format|
      format.html
      format.json { render json: @users }
      format.xml { render xml: @users }
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to Goodwill!"
      redirect_to @user

      respond_to do |format|
        format.html
        format.json { render json: @user, status: :created }
        format.xml { render xml: @user, status: :created }
      end
    else
      render 'new'

      respond_to do |format|
        format.html
        format.json { render json: @user.errors, status: :unprocessable_entity }
        format.xml { render xml: @user.errors, status: :unprocessable_entity }
      end
    end

  end

# PATCH/PUT /users/1
# PATCH/PUT /users/1.json
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user

      respond_to do |format|
        format.html
        format.json { head :no_content, status: :ok }
        format.xml { head :no_content, status: :ok }
      end

    else
      render 'edit'

      respond_to do |format|
        format.html
        format.json { render json: @user.errors, status: :unprocessable_entity }
        format.xml { render xml: @user.errors, status: :unprocessable_entity }
      end

    end


  end

# DELETE /users/1
# DELETE /users/1.json
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url

    respond_to do |format|
      if @user.destroy
        format.html
        format.json { head :no_content, status: :ok }
        format.xml { head :no_content, status: :ok }
      else
        format.html
        format.json { render json: @user.errors, status: :unprocessable_entity }
        format.xml { render xml: @user.errors, status: :unprocessable_entity }
      end
    end

  end


  def check_email
    user = User.find_by_email(params[:email])

    if user==nil
      respond_to do |format|
        format.json  { render :json => { :status => true, :message => "Email available!"} }
      end
    else
      respond_to do |format|
        format.json  { render :json => { :status => false, :message => "Email is taken!"} }
      end
    end
  end

#private
#def signed_in_user
#  unless signed_in?
#    store_location
#    redirect_to signin_url, notice: "Please sign in."
#  end
#end
#
#def correct_user
#  @user = User.find(params[:id])
#  redirect_to(root_url) unless current_user?(@user)
#end
#
#def admin_user
#  redirect_to(root_url) unless current_user.admin?
#end


  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Goodwill"
  end
end

app/helpers/products_helper.rb
module ProductsHelper

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to full_title(yield(:title)), root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Users", users_path %></li>
          <li><%= link_to "About", about_path %></li>
          <% if user_signed_in? %>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Sign out", destroy_user_session_path, method: "delete" %>
                  </li>
                </ul>
              </li>
          <% else %>
              <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>

  <%= stylesheet_link_tag "custom", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>

<div class="container">
    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>

      <%= yield %>
</div>


</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_name %><br>
    <%= f.text_field :product_name %>
  </div>
  <div class="field">
    <%= f.label :product_price %><br>
    <%= f.text_field :product_price %>
  </div>
  <div class="field">
    <%= f.label :product_description %><br>
    <%= f.text_field :product_description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<%= render partial: 'shared/feed_item', collection: @feed_items %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="span9">
  <div class="row-fluid">
    <% @products.each do |product| %>
    <div class="span5 offset1">
      <h2 class = "pull-left"><%= product.product_name %></h2>
      <h2 class = "pull-right">$<%= product.product_price %></h2>
      <%= image_tag "480x300.gif" %>
      <%= link_to 'View details', product %>
    </div><!--/span-->
    <% end %>
  </div>
</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product name:</strong>
  <%= @product.product_name %>
</p>

<p>
  <strong>Product price:</strong>
  <%= @product.product_price %>
</p>

<p>
  <strong>Product description:</strong>
  <%= @product.product_description %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        The form contains <%= pluralize(object.errors.count, "error") %>.
      </div>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li>* <%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items %>
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
    <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<div class="row offset1">
  <div class="span6">

    <% if feed_item.image_uri %>
        <%= image_tag feed_item.image_uri %>
    <% else %>
        <%= image_tag "480x300.gif" %>
    <% end %>

  </div>

  <div class="span4" id="<%= feed_item.id %>">
    <br>
    <p class="product_name">Name: <%= feed_item.product_name %></p>
    <p class="product_price">Price: $<%= feed_item.product_price %></p>
    <br>
    <p>
      <%= feed_item.product_description %>
    </p>

    <div>
       <p class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
  </p>
      <p class="product_user">Created by: <%= link_to feed_item.user.username, feed_item.user %></p>


          <p class="p product_delete">

    <% if current_user==feed_item.user %>
        <%= link_to "Delete this item", feed_item, method: :delete,
                    data: {confirm: "You sure?"},
                    title: feed_item.product_name %>
    <% end %>
    </p>
    </div>
  </div>
</div>
<div class="row"><br></div>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>

<h1><%= yield(:title) %></h1>
<p>
  This is a website displaying goodwill stuffs for CMUSV students within campus.
</p>
<p>
  Our store address is NASA Ames Research Park, Bldg. 23, Moffett Field, CA 94035-0001.
</p>

app/views/static_pages/home.html.erb
<div>
  <div class="heading center"><h3>All Products</h3></div>
  <%= render 'shared/feed' %>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form',  object: f.object %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<% provide(:title, @user.username) %>
<div class="container span12">
  <% if @user.products.any? %>
      <div class="heading center"><h3>Your Products: <%= @user.products.count %> items</h3></div>

        <%= render partial: 'shared/feed_item', collection: @products %>
        <%= render @products %>
      <%= will_paginate @products %>
  <% end %>
</div>